# Generated by Django 2.1 on 2019-08-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
                ('age', models.DateField()),
                ('password', models.CharField(max_length=33)),
            ],
            options={
                'db_table': 'StudentPro',
            },
        ),
    ]
