# Generated by Django 2.1 on 2019-08-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpro',
            old_name='age',
            new_name='dob',
        ),
        migrations.AlterField(
            model_name='studentpro',
            name='password',
            field=models.CharField(default='57d1463c43', max_length=33),
        ),
    ]
