# Generated by Django 2.1 on 2019-08-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producerapp', '0002_auto_20190802_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpro',
            name='password',
            field=models.CharField(default='d0acbf6c17', max_length=33),
        ),
    ]
