# Generated by Django 2.1 on 2019-08-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producerapp', '0003_auto_20190802_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpro',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='studentpro',
            name='name',
        ),
        migrations.AddField(
            model_name='studentpro',
            name='first_name',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpro',
            name='last_name',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentpro',
            name='password',
            field=models.CharField(default='117b97ac93', max_length=33),
        ),
    ]
