# Generated by Django 2.1 on 2019-08-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producerapp', '0004_auto_20190802_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpro',
            name='password',
            field=models.CharField(default='670aba651e', max_length=33),
        ),
    ]
