# Generated by Django 2.1 on 2019-08-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producerapp', '0005_auto_20190802_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpro',
            name='password',
            field=models.CharField(default='e7a3f14b27', max_length=33),
        ),
    ]
